server:
  port: 8081
spring:
  config:
    activate:
      on-profile: local
  application:
    name: shop-style-local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost:9092/~/test;MODE=MYSQL
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true